version: "3.9"
networks:
  common:
    external:
      name: selenoid
services:
  selenoid:
    image: "aerokube/selenoid"
    networks:
      - common
    ports:
      - "4444:4444"
    volumes:
      - "./:/etc/selenoid/" # assumed current dir contains browsers.json
      - "c:/Testing/video:/opt/selenoid/video/"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/c/Testing/video
    command: ["-video-output-dir", "/opt/selenoid/video", "-container-network", "selenoid"]
  selenoid-ui:
    image: "aerokube/selenoid-ui"
    networks:
      - common
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: [ "--selenoid-uri", "http://selenoid:4444/" ]
  py:
    build: .
    depends_on:
      - selenoid
    networks:
      - common